name: main deploy
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: checkout from repo
      - uses: actions/setup-node@v4
        name: Set up node js
      - run: echo "install dependency"
      - run: npm ci
      - run: echo testing
      - run: npm run test
  lint:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
        name: checkout from repo
      - uses: actions/setup-node@v4
        name: Set up node js
      - run: echo "install dependency"
      - run: npm ci
      - run: echo running lint
      - run: npm run lint
  deploy: 
    runs-on: ubuntu-latest
    needs: lint 
    steps:
      - uses: actions/checkout@v4
        name: checkout from repo
      - uses: actions/setup-node@v4
        name: Set up node js
      - run: echo "install dependency"
      - run: npm ci
      - run: echo building
      - run: npm run build
