name: main deploy
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: checkout from repo
      - uses: actions/setup-node@v4
        name: Set up node js
      - name: install dependency
        run: npm ci
      - name: testing
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
        name: checkout from repo
      - uses: actions/setup-node@v4
        name: Set up node js
      - name: install dependency
        run: npm ci
      - name: running lint
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
        name: checkout from repo
      - uses: actions/setup-node@v4
        name: Set up node js
      - name: install dependency
        run: npm ci
      - name: build code
        run: npm run build
      - uses: actions/upload-artifact@v4
        with:
            name: dist-files
            path: dist


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
        - name: get build artifacts 
          uses: actions/download-artifact@v4
          with:
            name: dist-files
        - name: view files
          run: ls 